import type { HopCatalogEntry } from '../../types';

/**
 * Houblons.
 *
 * **Provenance** : les fourchettes d'acides alpha publiées par les obtenteurs, les
 * négociants et les fiches de récolte. Un houblon n'a pas *un* taux d'alpha mais une
 * fourchette qui bouge d'une année et d'un lot à l'autre — c'est la raison d'être de
 * `[min, max]` plutôt que d'un chiffre unique, qui serait faux dès la récolte suivante.
 *
 * Le rôle dit l'emploi et, quand ils comptent, les arômes dominants.
 */
/** Corps d'une entrée de houblon : la famille est posée à l'export, une fois. */
type HopEntry = Omit<HopCatalogEntry, 'family'>;

const HOP_ENTRIES: readonly HopEntry[] = [
  /* --- Amérisants et doubles usages ----------------------------------------------- */
  {
    id: 'hop-admiral',
    name: 'Admiral',
    origin: 'Royaume-Uni',
    role: 'Amérisant',
    spec: { alphaPct: [13, 16] },
  },
  {
    id: 'hop-apollo',
    name: 'Apollo',
    origin: 'États-Unis',
    role: 'Amérisant',
    spec: { alphaPct: [15, 19] },
  },
  {
    id: 'hop-bravo',
    name: 'Bravo',
    origin: 'États-Unis',
    role: 'Amérisant',
    spec: { alphaPct: [14, 17] },
  },
  {
    id: 'hop-cluster',
    name: 'Cluster',
    origin: 'États-Unis',
    role: 'Amérisant · rustique',
    spec: { alphaPct: [5.5, 8.5] },
  },
  {
    id: 'hop-columbus',
    name: 'Columbus',
    origin: 'États-Unis',
    role: 'Amérisant · résineux',
    aliases: ['CTZ', 'Tomahawk', 'Zeus'],
    spec: { alphaPct: [14, 18] },
  },
  {
    id: 'hop-galena',
    name: 'Galena',
    origin: 'États-Unis',
    role: 'Amérisant',
    spec: { alphaPct: [11, 14] },
  },
  {
    id: 'hop-herkules',
    name: 'Herkules',
    origin: 'Allemagne',
    role: 'Amérisant',
    spec: { alphaPct: [12, 17] },
  },
  {
    id: 'hop-magnum',
    name: 'Magnum',
    origin: 'Allemagne',
    role: 'Amérisant · neutre',
    spec: { alphaPct: [12, 15] },
  },
  {
    id: 'hop-nugget',
    name: 'Nugget',
    origin: 'États-Unis',
    role: 'Amérisant',
    spec: { alphaPct: [11, 14] },
  },
  {
    id: 'hop-polaris',
    name: 'Polaris',
    origin: 'Allemagne',
    role: 'Amérisant · mentholé',
    spec: { alphaPct: [18, 21] },
  },
  {
    id: 'hop-summit',
    name: 'Summit',
    origin: 'États-Unis',
    role: 'Amérisant · orange',
    spec: { alphaPct: [16, 19] },
  },
  {
    id: 'hop-target',
    name: 'Target',
    origin: 'Royaume-Uni',
    role: 'Amérisant',
    spec: { alphaPct: [9.5, 12.5] },
  },
  {
    id: 'hop-waimea',
    name: 'Waimea',
    origin: 'Nouvelle-Zélande',
    role: 'Amérisant · pin, agrumes',
    spec: { alphaPct: [16, 19] },
  },
  {
    id: 'hop-aurora',
    name: 'Aurora',
    origin: 'Slovénie',
    role: 'Double usage · épicé, résineux',
    spec: { alphaPct: [7, 9] },
  },
  {
    id: 'hop-centennial',
    name: 'Centennial',
    origin: 'États-Unis',
    role: 'Double usage · agrumes',
    aliases: ['super cascade'],
    spec: { alphaPct: [9.5, 11.5] },
  },
  {
    id: 'hop-challenger',
    name: 'Challenger',
    origin: 'Royaume-Uni',
    role: 'Double usage · épicé, fruits cuits',
    spec: { alphaPct: [6.5, 8.5] },
  },
  {
    id: 'hop-chinook',
    name: 'Chinook',
    origin: 'États-Unis',
    role: 'Double usage · résineux, pamplemousse',
    spec: { alphaPct: [12, 14] },
  },
  {
    id: 'hop-dr-rudi',
    name: 'Dr. Rudi',
    origin: 'Nouvelle-Zélande',
    role: 'Double usage · agrumes, résineux',
    spec: { alphaPct: [9, 11] },
  },
  {
    id: 'hop-northern-brewer',
    name: 'Northern Brewer',
    origin: 'Allemagne',
    role: 'Double usage · boisé',
    spec: { alphaPct: [7, 10] },
  },
  {
    id: 'hop-perle',
    name: 'Perle',
    origin: 'Allemagne',
    role: 'Double usage · épicé',
    spec: { alphaPct: [6, 9] },
  },
  {
    id: 'hop-simcoe',
    name: 'Simcoe',
    origin: 'États-Unis',
    role: 'Double usage · résineux, agrumes',
    spec: { alphaPct: [12, 14] },
  },

  /* --- Aromatiques : agrumes et tropical ------------------------------------------ */
  {
    id: 'hop-amarillo',
    name: 'Amarillo',
    origin: 'États-Unis',
    role: 'Aromatique · orange, pêche',
    spec: { alphaPct: [8, 11] },
  },
  {
    id: 'hop-azacca',
    name: 'Azacca',
    origin: 'États-Unis',
    role: 'Aromatique · tropical, agrumes',
    spec: { alphaPct: [10, 15] },
  },
  {
    id: 'hop-cascade',
    name: 'Cascade',
    origin: 'États-Unis',
    role: 'Aromatique · pamplemousse, floral',
    spec: { alphaPct: [4.5, 7] },
  },
  {
    id: 'hop-cashmere',
    name: 'Cashmere',
    origin: 'États-Unis',
    role: 'Aromatique · citron vert, tropical',
    spec: { alphaPct: [7, 9] },
  },
  {
    id: 'hop-citra',
    name: 'Citra',
    origin: 'États-Unis',
    role: 'Aromatique · agrumes, fruits de la passion',
    spec: { alphaPct: [11, 13] },
  },
  {
    id: 'hop-comet',
    name: 'Comet',
    origin: 'États-Unis',
    role: 'Aromatique · agrumes',
    spec: { alphaPct: [9, 11] },
  },
  {
    id: 'hop-el-dorado',
    name: 'El Dorado',
    origin: 'États-Unis',
    role: 'Aromatique · fruits tropicaux',
    spec: { alphaPct: [13, 16] },
  },
  {
    id: 'hop-ekuanot',
    name: 'Ekuanot',
    origin: 'États-Unis',
    role: 'Aromatique · fruits, herbacé',
    aliases: ['Equinox'],
    spec: { alphaPct: [13, 16] },
  },
  {
    id: 'hop-galaxy',
    name: 'Galaxy',
    origin: 'Australie',
    role: 'Aromatique · fruit de la passion',
    spec: { alphaPct: [13, 15] },
  },
  {
    id: 'hop-idaho-7',
    name: 'Idaho 7',
    origin: 'États-Unis',
    role: 'Aromatique · fruits, résineux',
    spec: { alphaPct: [11, 13] },
  },
  {
    id: 'hop-mandarina-bavaria',
    name: 'Mandarina Bavaria',
    origin: 'Allemagne',
    role: 'Aromatique · mandarine',
    spec: { alphaPct: [7, 10] },
  },
  {
    id: 'hop-mosaic',
    name: 'Mosaic',
    origin: 'États-Unis',
    role: 'Aromatique · tropical, myrtille',
    spec: { alphaPct: [11, 13] },
  },
  {
    id: 'hop-motueka',
    name: 'Motueka',
    origin: 'Nouvelle-Zélande',
    role: 'Aromatique · citron vert',
    spec: { alphaPct: [6.5, 8.5] },
  },
  {
    id: 'hop-nelson-sauvin',
    name: 'Nelson Sauvin',
    origin: 'Nouvelle-Zélande',
    role: 'Aromatique · vin blanc, groseille',
    spec: { alphaPct: [11, 13] },
  },
  {
    id: 'hop-pacifica',
    name: 'Pacifica',
    origin: 'Nouvelle-Zélande',
    role: 'Aromatique · orange',
    spec: { alphaPct: [5, 6] },
  },
  {
    id: 'hop-rakau',
    name: 'Rakau',
    origin: 'Nouvelle-Zélande',
    role: 'Aromatique · fruits à noyau',
    spec: { alphaPct: [9, 11] },
  },
  {
    id: 'hop-sabro',
    name: 'Sabro',
    origin: 'États-Unis',
    role: 'Aromatique · coco, tropical',
    spec: { alphaPct: [12, 15] },
  },
  {
    id: 'hop-sorachi-ace',
    name: 'Sorachi Ace',
    origin: 'Japon',
    role: 'Aromatique · citron, aneth',
    spec: { alphaPct: [10, 14] },
  },
  {
    id: 'hop-strata',
    name: 'Strata',
    origin: 'États-Unis',
    role: 'Aromatique · résineux, fruits',
    spec: { alphaPct: [11, 13] },
  },
  {
    id: 'hop-vic-secret',
    name: 'Vic Secret',
    origin: 'Australie',
    role: 'Aromatique · tropical, ananas',
    spec: { alphaPct: [14, 17] },
  },
  {
    id: 'hop-wai-iti',
    name: 'Wai-iti',
    origin: 'Nouvelle-Zélande',
    role: 'Aromatique · mandarine, citron vert',
    spec: { alphaPct: [2.5, 4.5] },
  },

  /* --- Aromatiques : nobles et européens ------------------------------------------ */
  {
    id: 'hop-ekg',
    name: 'East Kent Goldings',
    origin: 'Royaume-Uni',
    role: 'Aromatique · floral, miel',
    aliases: ['EKG', 'Golding', 'Goldings'],
    spec: { alphaPct: [4, 7] },
  },
  {
    id: 'hop-fuggle',
    name: 'Fuggle',
    origin: 'Royaume-Uni',
    role: 'Aromatique · terreux, boisé',
    spec: { alphaPct: [4, 5.5] },
  },
  {
    id: 'hop-bramling-cross',
    name: 'Bramling Cross',
    origin: 'Royaume-Uni',
    role: 'Aromatique · cassis, épicé',
    spec: { alphaPct: [5, 7] },
  },
  {
    id: 'hop-hallertau-mittelfruh',
    name: 'Hallertau Mittelfrüh',
    origin: 'Allemagne',
    role: 'Aromatique · noble, épicé',
    aliases: ['Mittelfruh', 'Hallertauer'],
    spec: { alphaPct: [3, 5.5] },
  },
  {
    id: 'hop-hallertau-tradition',
    name: 'Hallertau Tradition',
    origin: 'Allemagne',
    role: 'Aromatique · noble',
    spec: { alphaPct: [4.5, 6.5] },
  },
  {
    id: 'hop-hersbrucker',
    name: 'Hersbrucker',
    origin: 'Allemagne',
    role: 'Aromatique · noble, herbacé',
    spec: { alphaPct: [2.5, 5] },
  },
  {
    id: 'hop-huell-melon',
    name: 'Huell Melon',
    origin: 'Allemagne',
    role: 'Aromatique · melon, fraise',
    spec: { alphaPct: [6, 8] },
  },
  {
    id: 'hop-loral',
    name: 'Loral',
    origin: 'États-Unis',
    role: 'Aromatique · floral, poivré',
    spec: { alphaPct: [10, 12] },
  },
  {
    id: 'hop-mount-hood',
    name: 'Mount Hood',
    origin: 'États-Unis',
    role: 'Aromatique · noble',
    spec: { alphaPct: [4, 7] },
  },
  {
    id: 'hop-saaz',
    name: 'Saaz',
    origin: 'Tchéquie',
    role: 'Aromatique · noble, épicé',
    aliases: ['Zatec'],
    spec: { alphaPct: [2.5, 4.5] },
  },
  {
    id: 'hop-spalt',
    name: 'Spalt',
    origin: 'Allemagne',
    role: 'Aromatique · noble',
    spec: { alphaPct: [3.5, 5.5] },
  },
  {
    id: 'hop-sterling',
    name: 'Sterling',
    origin: 'États-Unis',
    role: 'Aromatique · noble',
    spec: { alphaPct: [6, 9] },
  },
  {
    id: 'hop-styrian-goldings',
    name: 'Styrian Goldings',
    origin: 'Slovénie',
    role: 'Aromatique · floral, épicé',
    aliases: ['Celeia', 'Savinjski'],
    spec: { alphaPct: [3, 6] },
  },
  {
    id: 'hop-tettnanger',
    name: 'Tettnanger',
    origin: 'Allemagne',
    role: 'Aromatique · noble',
    spec: { alphaPct: [3, 5] },
  },
  {
    id: 'hop-crystal',
    name: 'Crystal',
    origin: 'États-Unis',
    role: 'Aromatique · épicé',
    spec: { alphaPct: [3.5, 5.5] },
  },
  {
    id: 'hop-ella',
    name: 'Ella',
    origin: 'Australie',
    role: 'Aromatique · floral, anis',
    spec: { alphaPct: [14, 16] },
  },
  {
    id: 'hop-willamette',
    name: 'Willamette',
    origin: 'États-Unis',
    role: 'Aromatique · terreux, floral',
    spec: { alphaPct: [4, 6] },
  },
];

export const HOPS: readonly HopCatalogEntry[] = HOP_ENTRIES.map(
  (entry): HopCatalogEntry => ({ ...entry, family: 'hop' }),
);
